---
title: "Tyler_WorkingFile"
author: "me"
date: "2026-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(gridExtra)
library(grid)
library(RColorBrewer)
library(ggrepel)
library(ggthemes)
library(viridis)
library(ggridges)
```

## Data Prep

```{r}
df <- read.csv('ufo_sighting_data.csv',sep=',',stringsAsFactors=F)
df$latitude <- as.numeric(df$latitude)
df$year <- sapply(df$Date_time, function(x) as.numeric(strsplit(strsplit(x," ")[[1]][1],"/")[[1]][3]))
df$month <- sapply(df$Date_time, function(x) as.numeric(strsplit(strsplit(x," ")[[1]][1],"/")[[1]][1]))
df$day <- sapply(df$Date_time, function(x) as.numeric(strsplit(strsplit(x," ")[[1]][1],"/")[[1]][2]))
df$hour <- sapply(df$Date_time, function(x) as.numeric(strsplit(strsplit(x," ")[[1]][2],":")[[1]][1]))
df$hour <- ifelse(df$hour==24,0,df$hour)
df$min <- sapply(df$Date_time, function(x) as.numeric(strsplit(strsplit(x," ")[[1]][2],":")[[1]][2]))
df$month_name <- sapply(df$month, function(x) month.name[x])
df$month_name_ordered <- factor(df$month_name, levels =c(month.name))
df$DATE <- sapply(df$Date_time, function(x) strsplit(x,' ')[[1]][1])
df$DATE_2 <- as.Date(df$DATE,"%m/%d/%Y")
df$weekday <- factor(weekdays(df$DATE_2, T), levels = rev(c("Mon", "Tue", "Wed", "Thu","Fri", "Sat", "Sun")))
df$length_min <- as.numeric(df$length_of_encounter_seconds)/60

blank_theme <- theme_fivethirtyeight()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )
```

## Overview

```{r}
g2 <- df %>% 
  group_by(year,country) %>% 
  summarize(count=n()) %>%
  ggplot(aes(x=year,y=count,fill=country)) + 
  geom_histogram(stat='identity',width=1,color='white',size=.25) + 
  scale_fill_brewer(palette='Paired') + geom_vline(xintercept=1993,color='black') + 
  annotate("text", x = 1990, y = 6000, label = "Internet access\nto general public",color='black') + 
  theme_fivethirtyeight() + 
  ggtitle('UFO Sightings Overview by Year and Location', 'NA, Australia, Canada, Germany, Great Britain, United States') + 
  theme(legend.position='right',legend.direction='vertical')

g2
```

## Country Plot

```{r}
countries_map <- map_data("world")
world_map <- ggplot() + 
  geom_map(data = countries_map, 
           map = countries_map,aes(x = long, y = lat, map_id = region, group = group),
           fill = "white", color = "black", size = 0.1)

world_map + geom_point(data=df,aes(x=longitude,y=latitude),alpha=.5,size=.25) + theme_fivethirtyeight() + ggtitle('Locations of UFO Sightings')
```


## U.S. Plot

```{r}
states_map <- map_data("state")

usMap <- ggplot() + 
  geom_map(data = states_map, map = states_map,aes(x = long, y = lat, map_id = region, group = group),fill = "white", color = "black", size = 0.1) + 
  theme_fivethirtyeight()

usMap + 
  geom_point(data=filter(df,country=='us' & state.province!='hi' & state.province!='ak' & state.province!='pr'),aes(x=longitude,y=latitude),alpha=.75,size=.5) + 
  ggtitle('Location of UFO Sightings in the US')

ggplot(df, aes(x=reorder(state.province, state.province, FUN=length), fill=state.province)) + 
  stat_count() +
  theme_bw() + theme(axis.text.x = element_text(angle=50, size=8, hjust=1)) + 
  xlab("State") + ylab("Number of appearances") + ggtitle("UFO sightings by states in the USA");
```


## Observations During the Day

```{r}
df %>% group_by(hour,month_name_ordered) %>% 
  summarize(count=n()) %>% 
  ggplot(aes(x=factor(hour),y=count,color=month_name_ordered,group=month_name_ordered)) + 
  geom_line() + 
  theme_fivethirtyeight() + 
  scale_color_manual(name="",values=brewer.pal(12,'Paired')) + 
  geom_point(color='black',size=.5,alpha=1) + 
  ggtitle('UFO Observations During the Day','Time Based on 24-hour Cycle')

```

```{r}
df %>% group_by(weekday,month_name_ordered) %>% 
  summarize(count=n()) %>% 
  ggplot(aes(x=weekday,y=count,color=month_name_ordered,group=month_name_ordered)) + 
  geom_line() + 
  theme_fivethirtyeight() + 
  scale_color_brewer(name="",palette='Paired') + 
  geom_point(color='black',size=.5,alpha=1) + 
  ggtitle('UFO Observations During the Week')
```
## Duration of Encounters

```{r}
df %>% filter(length_min>1e6) %>% 
  select(-c(length_of_encounter_seconds,DATE_2,description,year, month, day ,hour, min, month_name, month_name_ordered,state.province))
```

## Shapes of Encounters

```{r}
ggplot(df, aes(x=reorder(UFO_shape, UFO_shape, FUN=length), fill=UFO_shape)) + 
  geom_bar(show.legend=F) +
  coord_flip() +
  theme_bw() + xlab("UFO Shape") + ylab("Number of Appearances") + ggtitle("UFO Shapes Seen Worldwide");
```


```{r}
glimpse(df)

df %>% arrange(Date_time)
```
